### ISSUE TITLE
justinrainbow/json-schema 2.0 support

### ISSUE THREAD

**Issue by pies** [alecsammon/php-raml-parser#101]
I've investigated the possibility of updating the json-schema parser to 2.0, but the problem is that it has no notion of parsing a string. It could of course be worked out by extending the json-schema parser to be able to parse strings, but wouldn't it make sense to just resolve things as they are loaded (as that parser does)?

Is the two-stage first-load-then-parse process necessary?

**Comment by latrek** [comment]
Hi, are there any plans to update justinrainbow/json-schema to 2.0 or a newer version? With this old version its not possible to load rekursive schemas. Did you get it running with version 2.0 ?

**Comment by duxet** [comment]
[thephpleague/json-guard](https://github.com/thephpleague/json-guard) seems to be a good alternative for justinrainbow/json-schema. They claim it's working with circular dependencies, which is not a case with the currently used library.

**Comment by martin-georgiev** [comment]
With v3.0.0 the package moved to v5.0 of justinrainbow/json-schema
