### ISSUE TITLE
Use webmozart/json

### ISSUE THREAD

**Issue by Toflar** [alecsammon/php-raml-parser#40]
Hey Alec,

You may want to use https://github.com/webmozart/json for version 1. It seems like it would cover some of your schema validation already and seems to be a bit more robust :)

Awesome work!

**Comment by alecsammon** [comment]
Looks good. 

I'm swamped with real work at the moment - but will try and get it integrated asap - hopefully by the end of the week.

**Comment by Toflar** [comment]
No worries, I'm excited by your project anyway :) Just make sure it doesn't die!

**Comment by alecsammon** [comment]
Thank you. It's a critical part of the infrastructure at my work, and has some other awesome contributors. It's not going to die ;)
