### ISSUE TITLE
Protocols should be uppercase

### ISSUE THREAD

**Issue by Toflar** [alecsammon/php-raml-parser#42]
I tried to specify the following RAML:

```
protocols: [ HTTPS ]
```

and I ran into a `Not a valid protocol` `RamlParserException`.
When tracking this down I found that in `ApiDefinition` the constants are lower case: https://github.com/alecsammon/php-raml-parser/blob/1.0.0/src/ApiDefinition.php#L21

However, according to the spec, I think it should validate against uppercase: http://raml.org/spec.html#protocols

What's your opinion on that topic? :)

**Comment by alecsammon** [comment]
Yeah - looks like a bug.

My test coverage for v1.0.0 is really poor - hence not releasing it as stable yet.

Feel free to put a pull request in.

**Comment by Toflar** [comment]
Done :)
