### ISSUE TITLE
parse() should expect a string, not a file path

### ISSUE THREAD

**Issue by Toflar** [alecsammon/php-raml-parser#46]
One thing that bothered me when doing unit tests was that mass of fixtures due to the fact that `parse()` expects a path and you cannot just pass a string.
I think this part of the library should be improved. It relies on the SF2 Yaml component and cannot be substituted. Also, methods like `parseYaml` and `loadAndParseFile` etc. look like their specific to the SF2 Yaml component. 

What do you think about an interface and a default behavior implementing that interface and providing the current functionality? Or at least modify `parse()` in a way that it supports a direct string input?

**Comment by alecsammon** [comment]
Hi Yanick

I agree  :+1:  

It was one of those things that started just with my use case, and has quickly grown! 

I've started making some changes to this on the 1.0.0 branch, decoupling the yaml parser into a single call so it can be easily substituted. The php yaml parser has been shown to be much quicker, but fails for all but the most basic use cases - however it would be nice to use this if you wish, or use a different parser. Again - see the constructor of Raml\Parser on the 1.0.0 branch for how we've started to solve using different schema parsers and file loaders.

As for parsing a string instead of a file - this really is needed. I'm not sure whether parse() should accept either, and make a decision, or if we should have a parseFile() and parseString() method.

What are your thoughts? Are you happy to pick up some of these ideas and put a pull request in?

**Comment by Toflar** [comment]
> so it can be easily substituted.

It's `private` ;-)



> parse() should accept either, and make a decision, or if we should have a parseFile() and parseString() method.

No, it should either accept `string` only or something like a `Raml\Parser\ContentProviderInterface`.
Can be really simple! Something like

```php
interface ContentProviderInterface
{
    /**
     * Returns the content as an array
     *
     * @return  array
     */
    public function getContent();
}
```

```php
class FileContentProvider implements ContentProviderInterface
{
    /**
     * File
     *
     * @var string
     */
    private $file = '';

    /**
     * Creates a new FileContentProvider
     *
     * @param   string $file Path to the file
     */
    public function __construct($file)
    {
        if (!is_file($file)) {
            throw new FileNotFoundException($file);
        }

        $this->file = $file;
    }
    
    /**
     * {@inheritdoc}
     */
    public function getContent()
    {
        return Yaml::parse(file_get_contents($this->file));
    }
}
```

```php
class StringContentProvider implements ContentProviderInterface
{
    /**
     * Content
     *
     * @var string
     */
    private $content = '';

    /**
     * Creates a new StringContentProvider
     *
     * @param   string $content
     */
    public function __construct($content)
    {
        $this->content = $content;
    }

    /**
     * {@inheritdoc}
     */
    public function getContent()
    {
        return Yaml::parse($this->content);
    }
}
```

And here we go :-)

```php
$yaml = <<<YAML
title: Home
content: |
  Welcome to the _Zencoder API_ Documentation
YAML;
$contentProvider = new StringContentProvider($yaml);
$apiDef = $parser->parse($contentProvider);
```

This
* introduces possibility for any source of the content to be parsed
* removes dependency on the yaml component. If you don't like it (for whatever reason) you are free to write your own provider using another one or even write one that supports Dependency Injection.

Thoughts?

**Comment by alecsammon** [comment]
Ah yes - awesome - looks good.

Are we happy changing the interface for parse()? - this would be a breaking change for everyone using the library.

**Comment by Toflar** [comment]
I don't know. To me, there is no stable version yet and you are basically refactoring everything for a first version so nobody should rely on the current API, right?
But if you don't like that we could go and instead of doing this

```php
public function parse(ContentProviderInterface $contentProvider, $parseSchemas = true)
```

go for 

```php
public function parse($contentProvider, $parseSchemas = true)
{
    // BC
    if (!$contentProvider instanceof ContentProviderInterface) {
        $contentProvider = new FileContentProvider($contentProvider);
    }
}
```

**Comment by alecsammon** [comment]
Hmm - I think you're right

so we go for 
```php
public function parse(ContentProviderInterface $contentProvider, $parseSchemas = true)
```

and if people complain it's an easy fix to implement your second option.

Are you happy to put a pull request in?

**Comment by Toflar** [comment]
> Are you happy to put a pull request in?

Yeah, sure! But it'll take a moment as I'll also want to build some `AbstractContentProvider` for the `!include` and caching thing that every provider needs ;-)

**Comment by alecsammon** [comment]
Hmm - looks like this causes an issue when loading a included raml file in a different directory.

Will add a test and see how we can fix

**Comment by Toflar** [comment]
Yeah, just create a PR and notify me if you want me to have a look at it but I'm pretty sure you'll figure it out on your own :D

**Comment by alecsammon** [comment]
I've pushed a broken test on 1.0.0 :)

**Comment by Toflar** [comment]
Checking

**Comment by Toflar** [comment]
Works perfectly fine for me, your test was just wrong :-D I've extended the test and found another bug in `Response`: https://github.com/alecsammon/php-raml-parser/pull/51

**Comment by alecsammon** [comment]
Cool - sorry the test was stupid!

There was an issue - but because I had used the filename song.json it was masked. Sorry - shouldn't file tickets in a rush! I've fixed that bug. 

Thanks for the pull request

**Comment by Toflar** [comment]
No worries! BTW, while writing the tests I found that `BodyInterface` (https://github.com/alecsammon/php-raml-parser/blob/1.0.0/src/BodyInterface.php) only requires `getMediaType()` but there are some more methods: https://github.com/alecsammon/php-raml-parser/blob/1.0.0/src/Body.php
However, I'm not quite sure if e.g. every body needs to implement a `getSchema()` method etc. It's just something that caught my eye. Maybe you wanna have a look at it?
