### ISSUE TITLE
[BUG?] Unable to require 1.0.0

### ISSUE THREAD

**Issue by CozyLife** [alecsammon/php-raml-parser#53]
For some reason Composer can't locate the 1.0.0 branch for PHP RAML Parser. I stuck it in require as ``` "alecsammon/php-raml-parser": "1.0.0" ``` and also tried setting the @dev flag and appending -dev with no luck. Originally my composer.json had a minimum stability of "dev", but I've since removed that for best practices. It was on there from the original repo I had the JSON from, so I tried requiring this repo with it on without any luck. Composer was scanning the tags for the repo, but not the branches.

I've been picking at this problem for some time now, and I'm starting to wonder if it's not my configuration that's the problem, but possibly something on the repository that's causing it. Can you look into it and let me know if it's something on your end, please?

**Comment by CozyLife** [comment]
I was able to grab it manually through Git, so it must have been something on my end. False alarm. For anyone who comes across this issue, I removed the entry from composer after I pulled the "master" branch. In Git, you'll need to checkout the desired branch.

**Comment by alecsammon** [comment]
Hi Rick,

No worries. I've now promoted 1.0.0 to a tag on master. Should be able to drop the "dev".

**Comment by CozyLife** [comment]
Great. Thank you.
