### ISSUE TITLE
[BUG] alecsammon/json-schema doesn't pull with composer.

### ISSUE THREAD

**Issue by cozylife** [alecsammon/php-raml-parser#67]
For some reason composer cannot find a version for alecsammon/json-schema, and therefore it cannot require it.

**Comment by alecsammon** [comment]
Strange

which version of composer are you running?

mine is 
```
Composer version 1.0-dev (a32c91914558a3ff293d83f7b99c49f4a7931798) 2015-04-18 18:11:12
```

Also - is this when trying to add my library as a dependency in your project, or just running standalone.

Any chance you can let me see your composer.json (if it has no private information)

**Comment by CozyLife** [comment]
My composer is the same version. I always update it before I pull updates for everything else.

```
Composer version 1.0-dev (a32c91914558a3ff293d83f7b99c49f4a7931798) 2015-04-18 18:11:12
```

My composer.json lists the following for your project under the the "require" section.
```
"alecsammon/php-raml-parser": "dev-master"
```

I've also listed the following under "repositories."

```
{ "type": "git", "url": "https://github.com/alecsammon/php-raml-parser" }
```

Nothing points directly to alecsammon/json-schema, so my guess is that it's pulling it from your [composer.json](https://github.com/alecsammon/php-raml-parser/blob/master/composer.json) file in alecsammon/php-raml-parser.

**Comment by xait-jon-havard-gundersen** [comment]
I think the issue is that you didn't update the composer.json file in the alecsammon/json-schema package, the name is still justinrainbow/json-schema

**Comment by CozyLife** [comment]
Also very useful: https://getcomposer.org/doc/articles/troubleshooting.md#package-not-found

**Comment by CozyLife** [comment]
Having to fight to get a third party repo is ridiculous. Let's just get Justin's repo updated with a pull request and be done with it. I'm sick of having to miss updates and fight the system.

**Comment by rdohms** [comment]
Yeah this is still an issue and this is a huge mess right now. 
Unless you add this to packagist no one will find it, otherwise its better to not rename the package and instruct people to bypass the repository and use your fork with the repository option.

**Comment by wvervuurt** [comment]
Geachte heer/mevrouw,

in verband met vakantie ben ik onbereikbaar t/m zondag 17 mei. 

Werkt uw dienst niet naar behoren of heeft u om een andere reden mijn aandacht nodig, stuur dan een sms-bericht aan 06-53447238.  Uw bericht wordt dan zo spoedig mogelijk afgehandeld.

Met vriendelijke groet,

Willem Vervuurt

================================

Hello,

I am on vacation until Sunday the 17th of May.

If your service is malfunctioning or if you require my attention for something else, please send a text message to +31653447238. Your message will be dealt with as soon as possible.

Best regards,
Willem

**Comment by alecsammon** [comment]
Ok - done more investigation into this - it's a nightmare I agree. Sorry, I hadn't appreciated quite how much it didn't work. Still unsure why it was working for me!

The only real solution is to get the bug fixes merged into Json Schema. I've split the original pull request into 2 separate ones as they concern different things. I've also added tests for one of them.
See https://github.com/justinrainbow/json-schema/pull/153 and https://github.com/justinrainbow/json-schema/pull/152. Hopefully it will now be easier for them to merge.

In the mean time I'll try to see if I can make some changes to this library so it can use the original repo.

**Comment by alecsammon** [comment]
So json-schema has been fixed. 2.0.0 is now pointing at the fixed version.

**Comment by cozylife** [comment]
Awesome. It appears that the changes could be backwards compatible. Can you please update 1.X with the change, too? Also, what new features, and backwards incompatible changes are part of 2.0?

**Comment by alecsammon** [comment]
Tagged 1.1.1 

Just working on 2.0.0. Main backwards incompatible changes are
- disabling of directory traversal by default
- removal of custom validators
- fix security settings format
