### ISSUE TITLE
Can't include version 2.0.0

### ISSUE THREAD

**Issue by cozylife** [alecsammon/php-raml-parser#81]
I think Version 2.0.0 needs to have a tag for Composer to pull it.

**Comment by alecsammon** [comment]
try ```"alecsammon/php-raml-parser": "2.0.*@dev"```

I don't want to tag it until I've got some confirmation from people that it works!

**Comment by cozylife** [comment]
That worked. Thanks. I'll let you know how it goes on my end.

**Comment by cozylife** [comment]
It still doesn't look like Version 2.0.0 fixed [issue #70](https://github.com/alecsammon/php-raml-parser/pull/70#issuecomment-106824305). From reviewing the source, I see that the security call data is still being merged with the main request. Do you intend to resolve the issue in Version 2.x.0?
