### ISSUE TITLE
Parser adds ID property to external JSON example

### ISSUE THREAD

**Issue by darh** [alecsammon/php-raml-parser#84]
I've run into a wierd situation -- JSON example, loaded from external file (!include) is changed by the parser - it contains ID element with path to itself. 

*PHPUnit output:*
```
phpunit --filter doesNotAddIdTo
PHPUnit 4.6.7 by Sebastian Bergmann and contributors.

Configuration read from /opt/web/vendor/alecsammon/php-raml-parser/phpunit.xml

F.

Time: 5.18 seconds, Memory: 9.25Mb

There was 1 failure:

1) ParseTest::doesNotAddIdToExternalExampleJson
External example should not contain forced ID property
Failed asserting that object of class "stdClass" does not have attribute "id".

/opt/web/vendor/alecsammon/php-raml-parser/test/ParseTest.php:793
/opt/web/vendor/phpunit/phpunit/src/TextUI/Command.php:151
/opt/web/vendor/phpunit/phpunit/src/TextUI/Command.php:103
```

([unit tests](https://github.com/alecsammon/php-raml-parser/compare/master...kendu:external-json-example-id-issue
))

*/external*
```
stdClass Object
(
    [title] => this is not an ID
    [id] => file:///opt/web/vendor/alecsammon/php-raml-parser/test/fixture/exampleWithoutId.json
)
```

*/internal*
```
stdClass Object
(
    [title] => this is not an ID
)
```

Problem (for me) is that this breaks tests on my projects that validates all examples against JSON schema that has `"additionalProperties": false`.

For now -- I didn't dig in to try to fix this. Please advise.

**Comment by alecsammon** [comment]
Hi @darh,

Sorry for the delay.

Looks like this isn't added by my library, but by "justinrainbow/json-schema".

If you look at JsonSchema\Uri\UriRetriever line 155 you can see the line that adds it.

I'm not sure why they do this, haven't looked into it further. There is movement on that repo - may be worth checking with them.

Let me know what you find out.

**Comment by darh** [comment]
Thankyou. Will point them to this issue.
