### ISSUE TITLE
RAML 1.0

### ISSUE THREAD

**Issue by zender** [alecsammon/php-raml-parser#88]
Is RAML 1.0 supported?

**Comment by qutwala** [comment]
I won't create new issue, but I try to update this one with bugs in this package and features which is not supported at this moment but should be, according RAML 1.0 spec.

A few days ago I have noticed that examples provided *by path* in `DataType` files are not parsed and included in objects, hovewer using plain notion seems work.

Also not sure why but jsonschema validator fails on some schemas. I have not researched why yet, but for example having this schema: http://jsonapi.org/schema and this JSON:

``{``
  "data": [
    {
      "type": "country",
      "id": "101",
      "attributes": {
        "country": "India",
        "calling_code": [
          91
        ]
      }
    }
  ]
``}

validation will fail. You can use some online tools for quick testing, like: http://jsonschemalint.com/

**Comment by Assada** [comment]
+1

**Comment by martin-georgiev** [comment]
RAML 1.0 support is provided in [version series 3](https://github.com/alecsammon/php-raml-parser/tree/3.0.0)
RAML 0.8 support is provided in [version series 2](https://github.com/alecsammon/php-raml-parser/tree/2.3.0)
