### ISSUE TITLE
Define minimal php version required

### ISSUE THREAD

**Issue by JMLamodiere** [alecsammon/php-raml-parser#91]
Currently, the `require` section of `composer.json` does not state the minimal php version supported by the lib. I've tried using it on PHP 5.3 (please don't judge ^^) but the code uses short array syntax `[]` supported since PHP 5.4.

It could be a great idea to decide which version is supported, and add it in `composer.json`. Does someone knows if PHP 5.4 is enough for this lib ? Or knows about a cool static code analyser that can check that ?

I can push a PR, but basically you just have to add it : 

```yml
...
  "require": {
    "php": ">=5.4",
    ...
```

**Comment by alecsammon** [comment]
Don't worry - I won't judge you!

I'm running php 5.5 - however the tests pass in 5.4 so assuming that it must be supported:
https://travis-ci.org/alecsammon/php-raml-parser/jobs/94889220

**Comment by alecsammon** [comment]
testing branch: https://github.com/alecsammon/php-raml-parser/tree/update_composer

**Comment by JMLamodiere** [comment]
Ok thanks !

In your branch, you seems to have updated all of your `composer.lock` by launching a `composer update`. Problem is it now requires somes symfony 3 component, and they need `php >=5.5.9`

I've made another PR #92 , where I've run `composer update --lock`. It only fixes `composer.lock` (such as `hash` value) without altering libs versions.

Thanks for the lib by the way, very usefull to us :)

**Comment by alecsammon** [comment]
Thanks!
