### ISSUE TITLE
class Raml\ParseConfiguration not found in ... error message

### ISSUE THREAD

**Issue by gkimpson** [alecsammon/php-raml-parser#94]
I am getting errors stating Raml\ParseConfiguration not found in xyz...

    Class 'Raml\ParseConfiguration' not found in /cygdrive/c/src/myapp/Raml/Parser.php on line 83

Have I done a step incorrectly, what is the correct method to autoload the php-raml-parser? I have followed the instructions in the readme, i'm guessing I've done something wrong - any suggestions?

my index.php file -
    
    require ('Raml/Parser.php');
    use Raml\Parser;

    $parser = new \Raml\Parser();
    $filename= 'basic.raml';
    $apiDef = $parser->parse($filename, true);

    $title = $apiDef->getTitle();

**Comment by alecsammon** [comment]
Hi Gavin,

This project uses the composer autoloader. See https://getcomposer.org/doc/01-basic-usage.md#autoloading

You probably just need to replace this line:
```
require ('Raml/Parser.php');
```

with 
```
require __DIR__ . '/vendor/autoload.php';
```
